/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid_19;

/**
 *
 * @author asus
 */
public class GestionTunisie extends javax.swing.JPanel {

    /**
     * Creates new form GestionTunisie
     */
    public GestionTunisie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepays = new javax.swing.JTable();
        ajouterhopital = new javax.swing.JButton();
        majhopital = new javax.swing.JButton();
        effacer = new javax.swing.JButton();
        validerhopital = new javax.swing.JButton();
        panelgv = new javax.swing.JPanel();
        casj = new javax.swing.JLabel();
        casa = new javax.swing.JLabel();
        decesadultesgv = new javax.swing.JTextField();
        deceshgv = new javax.swing.JTextField();
        decesfgv = new javax.swing.JTextField();
        casjeunesgv = new javax.swing.JTextField();
        casadultesgv = new javax.swing.JTextField();
        cash = new javax.swing.JLabel();
        cashommesgv = new javax.swing.JTextField();
        casv = new javax.swing.JLabel();
        casf = new javax.swing.JLabel();
        casfemmesgv = new javax.swing.JTextField();
        gdecesgv = new javax.swing.JLabel();
        decesgvtext = new javax.swing.JTextField();
        gcasgv = new javax.swing.JLabel();
        gnomgv = new javax.swing.JLabel();
        nomgvtext = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        casgvtext = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        casvieuxgv = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        decesj = new javax.swing.JLabel();
        decesv = new javax.swing.JLabel();
        decesa = new javax.swing.JLabel();
        decesvieuxgv = new javax.swing.JTextField();
        decesh = new javax.swing.JLabel();
        decesf = new javax.swing.JLabel();
        decesjeunesgv = new javax.swing.JTextField();
        titre = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(35, 39, 67));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablepays.setAutoCreateRowSorter(true);
        tablepays.setBackground(new java.awt.Color(240, 240, 240));
        tablepays.setForeground(new java.awt.Color(240, 240, 240));
        tablepays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Date", "Total", "Vieux", "Adulte", "Jeune", "Femme", "Homme", "vieux", "Adulte", "Jeune", "Femme", "Homme"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepays.setGridColor(new java.awt.Color(240, 240, 240));
        tablepays.setSelectionForeground(new java.awt.Color(240, 240, 240));
        tablepays.setShowHorizontalLines(false);
        tablepays.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tablepays);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 1030, 200));

        ajouterhopital.setText("AJOUTER");
        ajouterhopital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterhopitalActionPerformed(evt);
            }
        });
        jPanel1.add(ajouterhopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 120, 39));

        majhopital.setText("METTRE A JOUR");
        majhopital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majhopitalActionPerformed(evt);
            }
        });
        jPanel1.add(majhopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 120, 39));

        effacer.setText("EFFACER TOUT");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });
        jPanel1.add(effacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 120, 39));

        validerhopital.setText("AFFICHER");
        validerhopital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerhopitalActionPerformed(evt);
            }
        });
        jPanel1.add(validerhopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 120, 39));

        panelgv.setBackground(new java.awt.Color(35, 39, 67));
        panelgv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casj.setBackground(new java.awt.Color(255, 255, 255));
        casj.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        casj.setForeground(new java.awt.Color(211, 184, 184));
        casj.setText("Nombre de cas jeunes :");
        panelgv.add(casj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        casa.setBackground(new java.awt.Color(255, 255, 255));
        casa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        casa.setForeground(new java.awt.Color(211, 184, 184));
        casa.setText("Nombre de cas adultes :");
        panelgv.add(casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, -1));
        panelgv.add(decesadultesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 80, -1));
        panelgv.add(deceshgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 80, -1));
        panelgv.add(decesfgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 80, -1));
        panelgv.add(casjeunesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 80, -1));
        panelgv.add(casadultesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, -1));

        cash.setBackground(new java.awt.Color(255, 255, 255));
        cash.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cash.setForeground(new java.awt.Color(229, 177, 226));
        cash.setText("Nombre d'hommes :");
        panelgv.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 180, -1));
        panelgv.add(cashommesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 80, -1));

        casv.setBackground(new java.awt.Color(255, 255, 255));
        casv.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        casv.setForeground(new java.awt.Color(211, 184, 184));
        casv.setText("Nombre de cas vieux :");
        panelgv.add(casv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        casf.setBackground(new java.awt.Color(255, 255, 255));
        casf.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        casf.setForeground(new java.awt.Color(229, 177, 226));
        casf.setText("Nombre de femmes :");
        panelgv.add(casf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 180, -1));
        panelgv.add(casfemmesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 80, -1));

        gdecesgv.setBackground(new java.awt.Color(255, 255, 255));
        gdecesgv.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        gdecesgv.setForeground(new java.awt.Color(255, 255, 255));
        gdecesgv.setText("Nombre de décés :");
        panelgv.add(gdecesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        decesgvtext.setBackground(new java.awt.Color(35, 39, 67));
        decesgvtext.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        decesgvtext.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelgv.add(decesgvtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, -1));

        gcasgv.setBackground(new java.awt.Color(255, 255, 255));
        gcasgv.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        gcasgv.setForeground(new java.awt.Color(255, 255, 255));
        gcasgv.setText("Nombre de cas :");
        panelgv.add(gcasgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        gnomgv.setBackground(new java.awt.Color(255, 255, 255));
        gnomgv.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        gnomgv.setForeground(new java.awt.Color(255, 255, 255));
        gnomgv.setText("nom du gouvernorat :");
        panelgv.add(gnomgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        nomgvtext.setBackground(new java.awt.Color(35, 39, 67));
        nomgvtext.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nomgvtext.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelgv.add(nomgvtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 240, -1));
        panelgv.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, 10));

        casgvtext.setBackground(new java.awt.Color(35, 39, 67));
        casgvtext.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        casgvtext.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelgv.add(casgvtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 240, -1));
        panelgv.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 10));
        panelgv.add(casvieuxgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 80, -1));
        panelgv.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 240, -1));

        decesj.setBackground(new java.awt.Color(255, 255, 255));
        decesj.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        decesj.setForeground(new java.awt.Color(211, 184, 184));
        decesj.setText("Nombre de jeunes :");
        panelgv.add(decesj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, -1));

        decesv.setBackground(new java.awt.Color(255, 255, 255));
        decesv.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        decesv.setForeground(new java.awt.Color(211, 184, 184));
        decesv.setText("Nombre de vieux :");
        panelgv.add(decesv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 180, -1));

        decesa.setBackground(new java.awt.Color(255, 255, 255));
        decesa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        decesa.setForeground(new java.awt.Color(211, 184, 184));
        decesa.setText("Nombre d'adultes :");
        panelgv.add(decesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 160, -1));
        panelgv.add(decesvieuxgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 80, -1));

        decesh.setBackground(new java.awt.Color(255, 255, 255));
        decesh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        decesh.setForeground(new java.awt.Color(229, 177, 226));
        decesh.setText("Nombre d'hommes :");
        panelgv.add(decesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 180, -1));

        decesf.setBackground(new java.awt.Color(255, 255, 255));
        decesf.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        decesf.setForeground(new java.awt.Color(229, 177, 226));
        decesf.setText("Nombre de femmes :");
        panelgv.add(decesf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 180, -1));
        panelgv.add(decesjeunesgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 80, -1));

        titre.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(0, 153, 153));
        titre.setText("Ajouter gouvernorat:");
        panelgv.add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(panelgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -10, 640, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterhopitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterhopitalActionPerformed
        // TODO add your handling code here:
        panelgv.show();
        gcasgv.setText("Nombre de cas :");
        gdecesgv.setText("Nombre de décés :");
        titre.setText("Ajouter pays :");
    }//GEN-LAST:event_ajouterhopitalActionPerformed

    private void majhopitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majhopitalActionPerformed
        // TODO add your handling code here:
        panelgv.show();
        gcasgv.setText("Nombre de cas nouveaux :");
        gdecesgv.setText("Nombre de décés nouveaux :");
        titre.setText("Mise à jour pays :");
    }//GEN-LAST:event_majhopitalActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed

// TODO add your handling code here:
        nomgvtext.setText("");
        casgvtext.setText("");
        casvieuxgv.setText("");
        casjeunesgv.setText("");
        casadultesgv.setText("");
        casfemmesgv.setText("");
        cashommesgv.setText("");
        decesvieuxgv.setText("");
        decesadultesgv.setText("");
        decesjeunesgv.setText("");
        decesfgv.setText("");
        deceshgv.setText("");
        decesgvtext.setText("");
    }//GEN-LAST:event_effacerActionPerformed

    private void validerhopitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerhopitalActionPerformed
        // TODO add your handling code here:
        nomgvtext.setText("");
        casgvtext.setText("");
        casvieuxgv.setText("");
        casjeunesgv.setText("");
        casadultesgv.setText("");
        casfemmesgv.setText("");
        cashommesgv.setText("");
        decesvieuxgv.setText("");
        decesadultesgv.setText("");
        decesjeunesgv.setText("");
        decesfgv.setText("");
        deceshgv.setText("");
        decesgvtext.setText("");
        panelgv.hide();
    }//GEN-LAST:event_validerhopitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterhopital;
    private javax.swing.JLabel casa;
    private javax.swing.JTextField casadultesgv;
    private javax.swing.JLabel casf;
    private javax.swing.JTextField casfemmesgv;
    private javax.swing.JTextField casgvtext;
    private javax.swing.JLabel cash;
    private javax.swing.JTextField cashommesgv;
    private javax.swing.JLabel casj;
    private javax.swing.JTextField casjeunesgv;
    private javax.swing.JLabel casv;
    private javax.swing.JTextField casvieuxgv;
    private javax.swing.JLabel decesa;
    private javax.swing.JTextField decesadultesgv;
    private javax.swing.JLabel decesf;
    private javax.swing.JTextField decesfgv;
    private javax.swing.JTextField decesgvtext;
    private javax.swing.JLabel decesh;
    private javax.swing.JTextField deceshgv;
    private javax.swing.JLabel decesj;
    private javax.swing.JTextField decesjeunesgv;
    private javax.swing.JLabel decesv;
    private javax.swing.JTextField decesvieuxgv;
    private javax.swing.JButton effacer;
    private javax.swing.JLabel gcasgv;
    private javax.swing.JLabel gdecesgv;
    private javax.swing.JLabel gnomgv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton majhopital;
    private javax.swing.JTextField nomgvtext;
    private javax.swing.JPanel panelgv;
    private javax.swing.JTable tablepays;
    private javax.swing.JLabel titre;
    private javax.swing.JButton validerhopital;
    // End of variables declaration//GEN-END:variables
}
