/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid_19;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author GAMING
 */
public class GestionPays extends javax.swing.JPanel {

    /**
     * Creates new form GP
     */
    public GestionPays() {
        initComponents();
        remplirTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void remplirTable() 
    {
        try 
        {
            ConnexionDB cn = new ConnexionDB();
            ResultSet res = cn.getStmt().executeQuery("Select NOM, SUM(NBCAS), SUM(NBDECES) from pays group by nom");
            tablepays.setModel(DbUtils.resultSetToTableModel(res));
            cn.getConn().close();
            cn.getStmt().close();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public boolean tryParseInt(String value) 
    {
        try 
        {
            Integer.parseInt(value);
            return true;
        } 
        catch (NumberFormatException e) 
        {
            Home h = new Home();
            h.toFront();
            JOptionPane.showMessageDialog(h, value + " n'est pas un nombre !", "Attention", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tunis_centre1 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        ajouterpayspanel = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nompaysnv = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        nbcaslabel = new javax.swing.JLabel();
        ndecespaysnv = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        nbdeceslabel = new javax.swing.JLabel();
        ncaspaysnv = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        ajouterpays = new javax.swing.JButton();
        majpays = new javax.swing.JButton();
        effacer = new javax.swing.JButton();
        valider = new javax.swing.JButton();
        boolp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepays = new javax.swing.JTable();

        setBackground(new java.awt.Color(35, 39, 67));
        setForeground(new java.awt.Color(0, 153, 153));

        tunis_centre1.setBackground(new java.awt.Color(35, 39, 67));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tunis_centre1Layout = new javax.swing.GroupLayout(tunis_centre1);
        tunis_centre1.setLayout(tunis_centre1Layout);
        tunis_centre1Layout.setHorizontalGroup(
            tunis_centre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tunis_centre1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        tunis_centre1Layout.setVerticalGroup(
            tunis_centre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tunis_centre1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(35, 39, 67));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajouterpayspanel.setBackground(new java.awt.Color(35, 39, 67));
        ajouterpayspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titre.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(0, 153, 153));
        titre.setText("Ajouter un pays:");
        ajouterpayspanel.add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom du pays :");
        ajouterpayspanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        nompaysnv.setBackground(new java.awt.Color(35, 39, 67));
        nompaysnv.setForeground(new java.awt.Color(250, 239, 239));
        nompaysnv.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nompaysnv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nompaysnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nompaysnvActionPerformed(evt);
            }
        });
        ajouterpayspanel.add(nompaysnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, -1));
        ajouterpayspanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 240, 10));

        nbcaslabel.setBackground(new java.awt.Color(255, 255, 255));
        nbcaslabel.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        nbcaslabel.setForeground(new java.awt.Color(255, 255, 255));
        nbcaslabel.setText("Nombre de cas :");
        ajouterpayspanel.add(nbcaslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        ndecespaysnv.setBackground(new java.awt.Color(35, 39, 67));
        ndecespaysnv.setForeground(new java.awt.Color(250, 239, 239));
        ndecespaysnv.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ndecespaysnv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ajouterpayspanel.add(ndecespaysnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 240, -1));
        ajouterpayspanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 240, 10));

        nbdeceslabel.setBackground(new java.awt.Color(255, 255, 255));
        nbdeceslabel.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        nbdeceslabel.setForeground(new java.awt.Color(255, 255, 255));
        nbdeceslabel.setText("Nombre de décés :");
        ajouterpayspanel.add(nbdeceslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        ncaspaysnv.setBackground(new java.awt.Color(35, 39, 67));
        ncaspaysnv.setForeground(new java.awt.Color(250, 239, 239));
        ncaspaysnv.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ncaspaysnv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ajouterpayspanel.add(ncaspaysnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 240, -1));
        ajouterpayspanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 240, 10));

        jPanel1.add(ajouterpayspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 620, 310));

        jPanel2.setBackground(new java.awt.Color(35, 39, 67));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajouterpays.setText("AJOUTER");
        ajouterpays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterpaysActionPerformed(evt);
            }
        });
        jPanel2.add(ajouterpays, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 39));

        majpays.setText("METTRE A JOUR");
        majpays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majpaysActionPerformed(evt);
            }
        });
        jPanel2.add(majpays, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 39));

        effacer.setText("EFFACER TOUT");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });
        jPanel2.add(effacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 39));

        valider.setText("VALIDER");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        jPanel2.add(valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 39));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 230, 290));
        jPanel1.add(boolp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(35, 39, 67));

        tablepays.setBackground(new java.awt.Color(240, 240, 240));
        tablepays.setForeground(new java.awt.Color(51, 0, 51));
        tablepays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PAYS", "Date", "NOMBRE DE CAS", "NOMBRE DE DECES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepays.setGridColor(new java.awt.Color(240, 240, 240));
        tablepays.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(tablepays);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tunis_centre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tunis_centre1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void ajouterpaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterpaysActionPerformed
        ajouterpayspanel.show();
        nbcaslabel.setText("Nombre de cas :");
        nbdeceslabel.setText("Nombre de décés :");
        titre.setText("Ajouter un pays :");
        boolp.setText("1");
    }//GEN-LAST:event_ajouterpaysActionPerformed

    private void majpaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majpaysActionPerformed
        ajouterpayspanel.show();
        nbcaslabel.setText("Nouveaux cas :");
        nbdeceslabel.setText("Nouveaux décés :");
        titre.setText("Mise à jour du pays :");
        boolp.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_majpaysActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        // TODO add your handling code here:
        nompaysnv.setText("");
        ncaspaysnv.setText("");
        ndecespaysnv.setText("");
    }//GEN-LAST:event_effacerActionPerformed

    private void nompaysnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nompaysnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nompaysnvActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.toFront();
        int cas, deces;
        
        String nom = nompaysnv.getText();
        if (tryParseInt(ndecespaysnv.getText()) == false || tryParseInt(ncaspaysnv.getText()) == false || nom.equals("")) 
        {
            JOptionPane.showMessageDialog(h, "Verifiez les données SVP ! ", "Attention", JOptionPane.ERROR_MESSAGE);
        } 
        else 
        {
            cas = Integer.parseInt(ncaspaysnv.getText());
            deces = Integer.parseInt(ndecespaysnv.getText());
            pays p = new pays(nom, cas, deces);
            
            
            try 
            {
                ConnexionDB cn = new ConnexionDB();
                
                Date actuel = new Date();
                SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
                String date = forma.format(actuel);
                java.util.Date udob = forma.parse(date);
                java.sql.Date sqld = new java.sql.Date(udob.getTime());
                

                if (boolp.getText().equals("0")) 
                {
                    PreparedStatement ps1 = cn.getConn().prepareStatement("select * from PAYS where Upper(NOM) = upper(?)");
                    ps1.setString(1, p.getNom());
                    ResultSet rs1 = ps1.executeQuery();
                    if (!rs1.next()) {
                        h.toFront();
                        JOptionPane.showMessageDialog(h, p.getNom() + " N'existe pas !", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                    } 
                    else 
                    {
                        PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS), SUM(NBDECES) from PAYS where Upper(NOM) = upper(?)");
                        pss.setString(1, p.getNom().toUpperCase());
                        ResultSet rs = pss.executeQuery();
                        rs.next();
                        if ((rs.getInt(1) + p.getNbCas()) < (rs.getInt(2) + p.getNbDeces())) 
                        {
                            h.toFront();
                            JOptionPane.showMessageDialog(h, "Le nombre de déces supérieur au nombre de cas", "Illogique", JOptionPane.INFORMATION_MESSAGE);
                        } 
                        else 
                        {
                            PreparedStatement ps2 = cn.getConn().prepareStatement("insert into PAYS (NOM, NBCAS,NBDECES,DATEE) values (?,?,?,?)");
                            ps2.setString(1, p.getNom().toUpperCase());
                            ps2.setInt(2, p.getNbCas());
                            ps2.setInt(3, p.getNbDeces());
                            ps2.setDate(4, sqld);
                            int a = ps2.executeUpdate();
                        }
                    }
                } 
                else 
                {
                    if (p.getNbCas() < p.getNbDeces()) 
                    {
                        h.toFront();
                        JOptionPane.showMessageDialog(h, "Le nombre de déces supérieur au nombre de cas", "Illogique", JOptionPane.INFORMATION_MESSAGE);
                    } 
                    else 
                    {
                        PreparedStatement ps1 = cn.getConn().prepareStatement("select * from PAYS where Upper(NOM) = upper(?)");
                        ps1.setString(1, p.getNom());
                        ResultSet rs = ps1.executeQuery();
                        if (!rs.next()) 
                        {
                            PreparedStatement ps = cn.getConn().prepareStatement("insert into PAYS (NOM, NBCAS,NBDECES,DATEE) values (?,?,?,?)");
                            ps.setString(1, p.getNom().toUpperCase());
                            ps.setInt(2, p.getNbCas());
                            ps.setInt(3, p.getNbDeces());
                            ps.setDate(4, sqld);
                            int a = ps.executeUpdate();
                        } 
                        else 
                        {
                            h.toFront();
                            JOptionPane.showMessageDialog(h, p.getNom() + " existe déjà !", "Attention", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
                remplirTable();
                nompaysnv.setText("");
                ncaspaysnv.setText("");
                ndecespaysnv.setText("");
            } 
            catch (Exception e) 
            {
                
                System.out.println(e.getMessage());
            }

        }


    }//GEN-LAST:event_validerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterpays;
    private javax.swing.JPanel ajouterpayspanel;
    private javax.swing.JLabel boolp;
    private javax.swing.JButton effacer;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton majpays;
    private javax.swing.JLabel nbcaslabel;
    private javax.swing.JLabel nbdeceslabel;
    private javax.swing.JTextField ncaspaysnv;
    private javax.swing.JTextField ndecespaysnv;
    private javax.swing.JTextField nompaysnv;
    private javax.swing.JTable tablepays;
    private javax.swing.JLabel titre;
    private javax.swing.JPanel tunis_centre1;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
