/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid_19;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author GAMING
 */
public class GestionHopital extends javax.swing.JPanel {

    /**
     * Creates new form GH
     */
  
    public GestionHopital() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        nom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        titre1 = new javax.swing.JLabel();
        litdispo = new javax.swing.JLabel();
        litsdispo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cashospitalises = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cashosp = new javax.swing.JLabel();
        bsn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        besoins = new javax.swing.JTextArea();
        test = new javax.swing.JLabel();
        ajouterhopital = new javax.swing.JButton();
        majhopital = new javax.swing.JButton();
        effacer = new javax.swing.JButton();
        validerhopital = new javax.swing.JButton();
        nbtest = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        tunis_centre = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        gouvernorat = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(35, 39, 67));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTable.setAutoCreateRowSorter(true);
        JTable.setBackground(new java.awt.Color(240, 240, 240));
        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PAYS", "Gouvernorat", "LitsDispo", "CasHospital", "Besoins", "NbTest", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable.setFocusCycleRoot(true);
        JTable.setGridColor(new java.awt.Color(240, 240, 240));
        JTable.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(JTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 830, 200));

        nom.setBackground(new java.awt.Color(35, 39, 67));
        nom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 240, 10));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("nom de gouvernorat :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        titre1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        titre1.setForeground(new java.awt.Color(255, 204, 102));
        titre1.setText("Ajouter un hôpital:");
        jPanel1.add(titre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        litdispo.setBackground(new java.awt.Color(255, 255, 255));
        litdispo.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        litdispo.setForeground(new java.awt.Color(255, 255, 255));
        litdispo.setText("Lits disponibles:");
        jPanel1.add(litdispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        litsdispo.setBackground(new java.awt.Color(35, 39, 67));
        litsdispo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        litsdispo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(litsdispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 240, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 10));

        cashospitalises.setBackground(new java.awt.Color(35, 39, 67));
        cashospitalises.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cashospitalises.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(cashospitalises, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 240, 10));

        cashosp.setBackground(new java.awt.Color(255, 255, 255));
        cashosp.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        cashosp.setForeground(new java.awt.Color(255, 255, 255));
        cashosp.setText("Cas hospitalisés:");
        jPanel1.add(cashosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        bsn.setBackground(new java.awt.Color(255, 255, 255));
        bsn.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        bsn.setForeground(new java.awt.Color(255, 255, 255));
        bsn.setText("Besoins:");
        jPanel1.add(bsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        besoins.setColumns(20);
        besoins.setRows(5);
        jScrollPane1.setViewportView(besoins);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 240, 70));

        test.setBackground(new java.awt.Color(255, 255, 255));
        test.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        test.setForeground(new java.awt.Color(255, 255, 255));
        test.setText("nombre de tests effectués:");
        jPanel1.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        ajouterhopital.setText("AJOUTER");
        ajouterhopital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouterhopitalMousePressed(evt);
            }
        });
        ajouterhopital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterhopitalActionPerformed(evt);
            }
        });
        jPanel1.add(ajouterhopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 120, 39));

        majhopital.setText("METTRE A JOUR");
        jPanel1.add(majhopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 120, 39));

        effacer.setText("EFFACER TOUT");
        jPanel1.add(effacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 120, 39));

        validerhopital.setText("AFFICHER");
        validerhopital.setActionCommand("Afficher");
        validerhopital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                validerhopitalMousePressed(evt);
            }
        });
        validerhopital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerhopitalActionPerformed(evt);
            }
        });
        jPanel1.add(validerhopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 120, 39));

        nbtest.setBackground(new java.awt.Color(35, 39, 67));
        nbtest.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nbtest.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(nbtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 190, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 190, 10));

        tunis_centre.setBackground(new java.awt.Color(35, 39, 67));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tunis_centreLayout = new javax.swing.GroupLayout(tunis_centre);
        tunis_centre.setLayout(tunis_centreLayout);
        tunis_centreLayout.setHorizontalGroup(
            tunis_centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tunis_centreLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        tunis_centreLayout.setVerticalGroup(
            tunis_centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tunis_centreLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(tunis_centre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 10));

        gouvernorat.setBackground(new java.awt.Color(255, 51, 51));
        gouvernorat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gouvernorat de l'Ariana", "Gouvernorat de Béja", "Gouvernorat de Ben Arous", "Gouvernorat de Bizerte", "Gouvernorat de Gabès", "Gouvernorat de Gafsa", "Gouvernorat de Jendouba", "Gouvernorat de Kairouan", "Gouvernorat de Kasserine", "Gouvernorat de Kébili", "Gouvernorat du Kef", "Gouvernorat de Mahdia", "Gouvernorat de Manouba", "Gouvernorat de Médenine", "Gouvernorat de Monastir", "Gouvernorat de Nabeul", "Gouvernorat de Sfax", "Gouvernorat de Sidi Bouzid", "Gouvernorat de Siliana", "Gouvernorat de Sousse", "Gouvernorat de Tataouine", "Gouvernorat de Tozeur", "Gouvernorat de Tunis", "Gouvernorat de Zaghouan" }));
        jPanel1.add(gouvernorat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 210, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nom de hôpital :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void validerhopitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerhopitalActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_validerhopitalActionPerformed

    private void ajouterhopitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterhopitalActionPerformed


        
    }//GEN-LAST:event_ajouterhopitalActionPerformed

    private void validerhopitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerhopitalMousePressed
        // TODO add your handling code here:
    try {
                ConnexionDB conn= new ConnexionDB(); 
            ResultSet  rs = (conn.getStmt()).executeQuery("SELECT * from hopital");
             int i=0;
            while (rs.next()){
                 JTable.getModel().setValueAt((rs.getString(1)),i,0);
                 JTable.getModel().setValueAt((rs.getString(2)),i,1);
                 JTable.getModel().setValueAt((rs.getInt(3)),i,2);
                 JTable.getModel().setValueAt((rs.getInt(4)),i,3);
                 JTable.getModel().setValueAt((rs.getString(5)),i,4);
                 JTable.getModel().setValueAt((rs.getInt(6)),i,5);
                 JTable.getModel().setValueAt((rs.getDate(7)),i,6);
                 i++;
                  repaint();
               
             }
               
          repaint();
     
          
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        catch (NullPointerException e){
            e.printStackTrace();
        } 
   
    
                       
    }//GEN-LAST:event_validerhopitalMousePressed

    private void ajouterhopitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterhopitalMousePressed
        // TODO add your handling code here:
 
                
    }//GEN-LAST:event_ajouterhopitalMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton ajouterhopital;
    private javax.swing.JTextArea besoins;
    private javax.swing.JLabel bsn;
    private javax.swing.JLabel cashosp;
    private javax.swing.JTextField cashospitalises;
    private javax.swing.JButton effacer;
    private javax.swing.JComboBox gouvernorat;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel litdispo;
    private javax.swing.JTextField litsdispo;
    private javax.swing.JButton majhopital;
    private javax.swing.JTextField nbtest;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel test;
    private javax.swing.JLabel titre1;
    private javax.swing.JPanel tunis_centre;
    private javax.swing.JButton validerhopital;
    // End of variables declaration//GEN-END:variables
}
