/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid_19;


import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.*;


/**
 *
 * @author msi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */ 
  
    public Home() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_acceuil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_hopital = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_monde = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_Ghopital = new javax.swing.JPanel();
        txt2 = new javax.swing.JLabel();
        btn_Gmonde = new javax.swing.JPanel();
        txt3 = new javax.swing.JLabel();
        btn_tunisie = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_Gtunisie = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        monpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        gP1 = new covid_19.GestionPays();
        interfaceMonde1 = new covid_19.InterfaceMonde();
        interfaceHopital1 = new covid_19.InterfaceHopital();
        interfacePays1 = new covid_19.InterfacePays();
        gestionTunisie1 = new covid_19.GestionTunisie();
        gestionHopital1 = new covid_19.GestionHopital();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(35, 39, 67));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_acceuil.setBackground(new java.awt.Color(0, 153, 153));
        btn_acceuil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_acceuilFocusLost(evt);
            }
        });
        btn_acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_acceuilMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_home_32px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Accueil");

        javax.swing.GroupLayout btn_acceuilLayout = new javax.swing.GroupLayout(btn_acceuil);
        btn_acceuil.setLayout(btn_acceuilLayout);
        btn_acceuilLayout.setHorizontalGroup(
            btn_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_acceuilLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        btn_acceuilLayout.setVerticalGroup(
            btn_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_acceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(btn_acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, 50));

        btn_hopital.setBackground(new java.awt.Color(35, 39, 67));
        btn_hopital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionclicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_hospital_3_26px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Le suivi de l’état des hôpitaux en Tunisie");

        javax.swing.GroupLayout btn_hopitalLayout = new javax.swing.GroupLayout(btn_hopital);
        btn_hopital.setLayout(btn_hopitalLayout);
        btn_hopitalLayout.setHorizontalGroup(
            btn_hopitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_hopitalLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_hopitalLayout.setVerticalGroup(
            btn_hopitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(btn_hopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 410, -1));

        btn_monde.setBackground(new java.awt.Color(35, 39, 67));
        btn_monde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionclicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_mondeMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_location_50px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Le suivi de la pandémie dans le monde   "); // NOI18N

        javax.swing.GroupLayout btn_mondeLayout = new javax.swing.GroupLayout(btn_monde);
        btn_monde.setLayout(btn_mondeLayout);
        btn_mondeLayout.setHorizontalGroup(
            btn_mondeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_mondeLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 343, Short.MAX_VALUE))
            .addGroup(btn_mondeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_mondeLayout.createSequentialGroup()
                    .addContainerGap(63, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        btn_mondeLayout.setVerticalGroup(
            btn_mondeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addGroup(btn_mondeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        sidepane.add(btn_monde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 410, -1));

        btn_admin.setBackground(new java.awt.Color(35, 39, 67));
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adminMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_plus_math_32px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Administrateur"); // NOI18N

        javax.swing.GroupLayout btn_adminLayout = new javax.swing.GroupLayout(btn_admin);
        btn_admin.setLayout(btn_adminLayout);
        btn_adminLayout.setHorizontalGroup(
            btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_adminLayout.setVerticalGroup(
            btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_adminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        sidepane.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 410, 50));

        jPanel7.setBackground(new java.awt.Color(35, 39, 67));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_administrator_male_50px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UserName");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        sidepane.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 80));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, 240, 0));
        sidepane.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_settings_26px.png"))); // NOI18N
        sidepane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_sign_out_26px.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        sidepane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 40, 50));
        sidepane.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 280, 10));

        btn_Ghopital.setBackground(new java.awt.Color(35, 39, 67));
        btn_Ghopital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionclicked(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setText("La gestion des hôpitaux de la Tunisie");

        javax.swing.GroupLayout btn_GhopitalLayout = new javax.swing.GroupLayout(btn_Ghopital);
        btn_Ghopital.setLayout(btn_GhopitalLayout);
        btn_GhopitalLayout.setHorizontalGroup(
            btn_GhopitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_GhopitalLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        btn_GhopitalLayout.setVerticalGroup(
            btn_GhopitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_GhopitalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidepane.add(btn_Ghopital, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 420, 40));

        btn_Gmonde.setBackground(new java.awt.Color(35, 39, 67));
        btn_Gmonde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionclicked(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setText("La gestion des autres pays du monde");

        javax.swing.GroupLayout btn_GmondeLayout = new javax.swing.GroupLayout(btn_Gmonde);
        btn_Gmonde.setLayout(btn_GmondeLayout);
        btn_GmondeLayout.setHorizontalGroup(
            btn_GmondeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_GmondeLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        btn_GmondeLayout.setVerticalGroup(
            btn_GmondeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_GmondeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidepane.add(btn_Gmonde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 420, 40));

        btn_tunisie.setBackground(new java.awt.Color(35, 39, 67));
        btn_tunisie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionclicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8-tunisia-48.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Le suivi de la pandémie en Tunisie");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_tunisieLayout = new javax.swing.GroupLayout(btn_tunisie);
        btn_tunisie.setLayout(btn_tunisieLayout);
        btn_tunisieLayout.setHorizontalGroup(
            btn_tunisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tunisieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        btn_tunisieLayout.setVerticalGroup(
            btn_tunisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tunisieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(btn_tunisie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 410, 50));

        btn_Gtunisie.setBackground(new java.awt.Color(35, 39, 67));
        btn_Gtunisie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionclicked(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("La gestion des pays de la Tunisie");

        javax.swing.GroupLayout btn_GtunisieLayout = new javax.swing.GroupLayout(btn_Gtunisie);
        btn_Gtunisie.setLayout(btn_GtunisieLayout);
        btn_GtunisieLayout.setHorizontalGroup(
            btn_GtunisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_GtunisieLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        btn_GtunisieLayout.setVerticalGroup(
            btn_GtunisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_GtunisieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidepane.add(btn_Gtunisie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 40));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 730));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel14.setBackground(new java.awt.Color(35, 39, 67));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(35, 39, 67));
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1080, 80));

        monpanel.setBackground(new java.awt.Color(35, 39, 67));

        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(gP1, "card2");
        jPanel2.add(interfaceMonde1, "card4");
        jPanel2.add(interfaceHopital1, "card5");
        jPanel2.add(interfacePays1, "card6");
        jPanel2.add(gestionTunisie1, "card7");
        jPanel2.add(gestionHopital1, "card8");

        javax.swing.GroupLayout monpanelLayout = new javax.swing.GroupLayout(monpanel);
        monpanel.setLayout(monpanelLayout);
        monpanelLayout.setHorizontalGroup(
            monpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        monpanelLayout.setVerticalGroup(
            monpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monpanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(monpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 1070, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txt1.setForeground(new Color (35,39,67));
        txt2.setForeground(new Color (35,39,67));
        txt3.setForeground(new Color (35,39,67));
    }//GEN-LAST:event_formWindowOpened

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
        Login2 in = new Login2();
        this.dispose();
        in.setVisible(true);

    }//GEN-LAST:event_jLabel13MousePressed

    private void btn_adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMousePressed
        // TODO add your handling code here:
        resetColor(btn_tunisie);
        resetColor(btn_acceuil);
        resetColor(btn_hopital);
        resetColor(btn_monde);
        setColor(btn_admin);
         resetColor(btn_Gtunisie);
        resetColor(btn_Ghopital);
        resetColor(btn_Gmonde);
    }//GEN-LAST:event_btn_adminMousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:

        txt1.setForeground(new Color (255,255,255));
        txt2.setForeground(new Color (255,255,255));
        txt3.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_jLabel8MousePressed

    private void btn_mondeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mondeMousePressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btn_mondeMousePressed

    private void btn_acceuilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acceuilMousePressed
        // TODO add your handling code here:
        resetColor(btn_tunisie);
        setColor(btn_acceuil);
        resetColor(btn_hopital);
        resetColor(btn_monde);
        resetColor(btn_admin);
         resetColor(btn_Gtunisie);
        resetColor(btn_Ghopital);
        resetColor(btn_Gmonde);
    }//GEN-LAST:event_btn_acceuilMousePressed

    private void btn_acceuilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_acceuilFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acceuilFocusLost

    private void gestionclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionclicked
        // TODO add your handling code here:
      
        
       
        
        if (evt.getSource()==btn_tunisie)
        {
            setColor(btn_tunisie);
        resetColor(btn_acceuil);
        resetColor(btn_hopital);
        resetColor(btn_monde);
        resetColor(btn_admin);
        monpanel.setLayout(new BorderLayout());
        
        interfacePays1.setVisible(true);
        interfaceMonde1.setVisible(false);
        interfaceHopital1.setVisible(false);
        gestionHopital1.setVisible(false);
            gP1.setVisible(false);
            gestionTunisie1.setVisible(false);
        }
        else if (evt.getSource()==btn_monde)
        {
           resetColor(btn_tunisie);
        resetColor(btn_acceuil);
        resetColor(btn_hopital);
        resetColor(btn_admin);
        setColor(btn_monde);
         resetColor(btn_Gtunisie);
        resetColor(btn_Ghopital);
        resetColor(btn_Gmonde);
        monpanel.setLayout(new BorderLayout());
        
        
        interfaceMonde1.setVisible(true);
        
        
        interfacePays1.setVisible(false);
        interfaceHopital1.setVisible(false);
        gestionHopital1.setVisible(false);
            gP1.setVisible(false);
            gestionTunisie1.setVisible(false);
        }
        else if (evt.getSource()==btn_hopital)
        {
            resetColor(btn_tunisie);
        resetColor(btn_acceuil);
        resetColor(btn_admin);
        setColor(btn_hopital);
        resetColor(btn_monde);
         resetColor(btn_Gtunisie);
        resetColor(btn_Ghopital);
        resetColor(btn_Gmonde);
        
        monpanel.setLayout(new BorderLayout());
        
        interfaceHopital1.setVisible(true);
        
        interfacePays1.setVisible(false);
        interfaceMonde1.setVisible(false);
        gestionHopital1.setVisible(false);
            gP1.setVisible(false);
            gestionTunisie1.setVisible(false);
        }
        else if (evt.getSource()==btn_Gtunisie)
        {
            resetColor(btn_tunisie);
        resetColor(btn_acceuil);
        resetColor(btn_hopital);
        resetColor(btn_monde);
        setColor(btn_admin);
           setColor(btn_Gtunisie);
        resetColor(btn_Ghopital);
        resetColor(btn_Gmonde);
                 
                
                 
                 gP1.setVisible(false);
            
            interfacePays1.setVisible(false);
        interfaceMonde1.setVisible(false);
        interfaceHopital1.setVisible(false);
        gestionHopital1.setVisible(false);
           
            gestionTunisie1.setVisible(true);
        
        }
        else if (evt.getSource()==btn_Ghopital) 
        {
            resetColor(btn_Gtunisie);
        setColor(btn_Ghopital);
        resetColor(btn_Gmonde);
        //Définition setLayout
            gestionHopital1.setVisible(true);
            
            gP1.setVisible(false);
            
            
            
            interfacePays1.setVisible(false);
        interfaceMonde1.setVisible(false);
        interfaceHopital1.setVisible(false);
        
           
            gestionTunisie1.setVisible(false);
        }
        else if (evt.getSource()==btn_Gmonde)
        {
            resetColor(btn_Gtunisie);
        resetColor(btn_Ghopital);
        setColor(btn_Gmonde);
        GestionPays inter2 = new GestionPays();
        monpanel.setLayout(new BorderLayout());//Définition setLayout
           
            gP1.setVisible(true);
            
            interfacePays1.setVisible(false);
        interfaceMonde1.setVisible(false);
        interfaceHopital1.setVisible(false);
        gestionHopital1.setVisible(false);
           
            gestionTunisie1.setVisible(false);
            
        }
    }//GEN-LAST:event_gestionclicked
void setColor(JPanel panel){
    panel.setBackground(new Color(0,153,153));
}
void resetColor(JPanel panel){
        panel.setBackground(new Color(35,39,67));

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
        
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_Ghopital;
    private javax.swing.JPanel btn_Gmonde;
    private javax.swing.JPanel btn_Gtunisie;
    private javax.swing.JPanel btn_acceuil;
    private javax.swing.JPanel btn_admin;
    private javax.swing.JPanel btn_hopital;
    private javax.swing.JPanel btn_monde;
    private javax.swing.JPanel btn_tunisie;
    private covid_19.GestionPays gP1;
    private covid_19.GestionHopital gestionHopital1;
    private covid_19.GestionTunisie gestionTunisie1;
    private covid_19.InterfaceHopital interfaceHopital1;
    private covid_19.InterfaceMonde interfaceMonde1;
    private covid_19.InterfacePays interfacePays1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel monpanel;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    // End of variables declaration//GEN-END:variables
}
