/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid_19;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author GAMING
 */
public class InterfaceMonde extends javax.swing.JPanel {

    /**
     * Creates new form Interface33
     */
    public InterfaceMonde() {
        initComponents();
        remplirCombobox();
        totalCasGeneral();
        totaldecesGeneral();
        nvdecesGeneral();
        nvcasGeneral();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tunis_centre = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        actualiser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        actualiser1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        tunis_centre.setBackground(new java.awt.Color(0, 153, 153));
        tunis_centre.setPreferredSize(new java.awt.Dimension(1163, 657));
        tunis_centre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(255, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nom Pays" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        tunis_centre.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 274, 60));

        jLabel28.setText("Total Cases");

        jLabel29.setBackground(new java.awt.Color(0, 102, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 255));
        jLabel29.setText("11");

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_bandage_30px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel30))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel29)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(17, 17, 17)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(23, 23, 23))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tunis_centre.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        jLabel31.setText("New Cases");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 102, 51));
        jLabel32.setText("  0");

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_bandage_30px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tunis_centre.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 11, -1, -1));

        jLabel34.setText("New Deaths");
        jLabel34.setToolTipText("");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 153));
        jLabel35.setText("0");

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_death_26px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addContainerGap())
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(42, 42, 42))))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)))
                .addContainerGap())
        );

        tunis_centre.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 11, -1, -1));

        jLabel37.setText("Total Deaths");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 51, 0));
        jLabel38.setText("1");

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid_19/images/icons8_death_26px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel39))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel37)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        tunis_centre.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 11, -1, -1));

        jButton1.setText("Filtrer par pays");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tunis_centre.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 550, 110, -1));

        jCalendar1.setBackground(new java.awt.Color(204, 0, 204));
        jCalendar1.setToolTipText("");
        tunis_centre.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 356, 281));

        actualiser.setText("Actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });
        tunis_centre.add(actualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, -1, -1));

        jButton2.setText("Filtrer par date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        tunis_centre.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 440, 110, -1));

        actualiser1.setText("exporter les données");
        actualiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiser1ActionPerformed(evt);
            }
        });
        tunis_centre.add(actualiser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, -1, -1));

        jButton3.setText("Bar Chart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        tunis_centre.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        jButton4.setText("query");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        tunis_centre.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tunis_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tunis_centre, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
        remplirCombobox();
        totalCasGeneral();
        totaldecesGeneral();
        nvdecesGeneral();
        nvcasGeneral();
    }//GEN-LAST:event_actualiserActionPerformed

    private void caspays() {
        try {
            ConnexionDB cn = new ConnexionDB();

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS) from PAYS WHERE upper(NOM)=upper(?)");
            pss.setString(1, jComboBox1.getSelectedItem().toString());
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel29.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void decespays() {
        try {
            ConnexionDB cn = new ConnexionDB();

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBDECES) from PAYS WHERE upper(NOM)=upper(?)");
            pss.setString(1, jComboBox1.getSelectedItem().toString());
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel38.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void nvcaspays() {
        try {
            ConnexionDB cn = new ConnexionDB();

            Date actuel = new Date();
            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(actuel);
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS) from PAYS WHERE upper(NOM)=upper(?) and DATEE=?");
            pss.setString(1, jComboBox1.getSelectedItem().toString());
            pss.setDate(2, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel32.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void nvdecespays() {
        try {
            ConnexionDB cn = new ConnexionDB();

            Date actuel = new Date();
            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(actuel);
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBDECES) from PAYS WHERE upper(NOM)=upper(?) and DATEE=?");
            pss.setString(1, jComboBox1.getSelectedItem().toString());
            pss.setDate(2, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel35.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() != 0) {
            caspays();
            decespays();
            nvcaspays();
            nvdecespays();
        } else {
            Home h = new Home();
            h.toFront();
            JOptionPane.showMessageDialog(h, " Aucun pays séléctionné !", "Erreur", JOptionPane.INFORMATION_MESSAGE);
        }

        /*if (jCalendar1.getDate()!=null)
         {
         System.out.println(jCalendar1.getDate());
         }
         else System.out.println("prob");*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nvdecesdate() {
        try {
            ConnexionDB cn = new ConnexionDB();

            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(jCalendar1.getDate());
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBDECES) from PAYS WHERE DATEE=?");
            pss.setDate(1, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel35.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void nvcasdate() {
        try {
            ConnexionDB cn = new ConnexionDB();

            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(jCalendar1.getDate());
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS) from PAYS WHERE DATEE=?");
            pss.setDate(1, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel32.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void decesdate() {
        try {
            ConnexionDB cn = new ConnexionDB();

            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(jCalendar1.getDate());
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBDECES) from PAYS WHERE DATEE<=?");
            pss.setDate(1, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel38.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void casdate() {
        try {
            ConnexionDB cn = new ConnexionDB();

            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(jCalendar1.getDate());
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS) from PAYS WHERE DATEE<=?");
            pss.setDate(1, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel29.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        nvdecesdate();
        nvcasdate();
        decesdate();
        casdate();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void actualiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiser1ActionPerformed
        // TODO add your handling code here:
        String filepath = "C:\\Users\\asus\\Desktop\\cv\\exportpays.txt";
        File file = new File(filepath);
        try {
            ConnexionDB cn = new ConnexionDB();
            PreparedStatement pss = cn.getConn().prepareStatement("select NOM, SUM(NBCAS), SUM(NBDECES) from PAYS group by NOM");
            ResultSet rs = pss.executeQuery();
            rs.next();

            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("Nom ||");
            bw.write("Nombre de cas ||");
            bw.write("Nombre de deces");
            bw.newLine();
            bw.write("----------------------------------");
            bw.newLine();
            while (rs.next()) {
                bw.write(rs.getString(1) + "        ");
                bw.write(Integer.toString(rs.getInt(2)) + "           ");
                bw.write(Integer.toString(rs.getInt(3)));
                bw.newLine();

            }
            bw.close();
            fw.close();
            cn.getConn().close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_actualiser1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try 
        {
            
           
           
            
           ConnexionDB cn = new ConnexionDB();
           JDBCCategoryDataset ds = new  JDBCCategoryDataset(cn.getConn(),"select NOM, SUM(NBCAS) from PAYS group by NOM");
           JFreeChart chart = ChartFactory.createBarChart3D("Nombre de cas par Pays", "Pays", "Nombre de cas", ds, PlotOrientation.VERTICAL, false, true, false);
           chart.getTitle().setPaint(Color.BLUE);
           CategoryPlot p = chart.getCategoryPlot();
           p.setRangeGridlinePaint(Color.BLACK);
           
           
           ChartPanel chp = new ChartPanel(chart);
           chp.setVisible(true);
           chp.setSize(450, 350);
           
           
           this.removeAll();
           this.add(chp, BorderLayout.CENTER);
           this.validate();
           
           
        }
        catch (Exception e)
        {
            Home h = new Home();
            h.toFront();
            JOptionPane.showMessageDialog(h, e, "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try 
        {
           ConnexionDB cn = new ConnexionDB();
           JDBCCategoryDataset ds = new  JDBCCategoryDataset(cn.getConn(),"select DATEE, SUM(NBDECES) from PAYS group by DATEE Order by DATEE");
           JFreeChart chart = ChartFactory.createLineChart("Evaluation du nombre des déces par jour", "Date", "Nombre de déces", ds, PlotOrientation.VERTICAL, false, true, true);
           BarRenderer bar = null;
           CategoryPlot p = null;
           bar = new BarRenderer();
           
           
           ChartPanel chp = new ChartPanel(chart);
           chp.setVisible(true);
           chp.setSize(450, 350);
           
           
           this.removeAll();
           this.add(chp, BorderLayout.CENTER);
           this.validate();
           
           
        }
        catch (Exception e)
        {
            Home h = new Home();
            h.toFront();
            JOptionPane.showMessageDialog(h, e, "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void remplirCombobox() {
        try {
            ConnexionDB cn = new ConnexionDB();
            PreparedStatement pss = cn.getConn().prepareStatement("select distinct upper(NOM) from PAYS");
            ResultSet rs = pss.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString(1));
            }
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void totalCasGeneral() {
        try {
            ConnexionDB cn = new ConnexionDB();
            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS) from PAYS");
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel29.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void totaldecesGeneral() {
        try {
            ConnexionDB cn = new ConnexionDB();
            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBDECES) from PAYS");
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel38.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void nvdecesGeneral() {
        try {
            ConnexionDB cn = new ConnexionDB();

            Date actuel = new Date();
            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(actuel);
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBDECES) from PAYS WHERE DATEE=?");
            pss.setDate(1, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel35.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void nvcasGeneral() {
        try {
            ConnexionDB cn = new ConnexionDB();

            Date actuel = new Date();
            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String date = forma.format(actuel);
            java.util.Date udob = forma.parse(date);
            java.sql.Date sqld = new java.sql.Date(udob.getTime());

            PreparedStatement pss = cn.getConn().prepareStatement("select SUM(NBCAS) from PAYS WHERE DATEE=?");
            pss.setDate(1, sqld);
            ResultSet rs = pss.executeQuery();
            rs.next();
            int a = rs.getInt(1);
            jLabel32.setText(String.valueOf(a));
            cn.getConn().close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JButton actualiser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel tunis_centre;
    // End of variables declaration//GEN-END:variables
}
